version: '3'

services:
  openmind:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:80"

    extra_hosts:
      - "localhost:0.0.0.0"

    image: 'open-mind-backend'

    container_name: open-mind

    restart: on-failure

    depends_on:
      - open-mind-db

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://openmind-db:5432/open-mind
      - SPRING_DATASOURCE_USERNAME=openmind
      - SPRING_DATASOURCE_PASSWORD=openmind
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

    volumes:
      - openmind:/app/data
      - openmind_storage:/app/storage


  open-mind-db:
    image: 'postgres:13.1-alpine'
    container_name: open-mind-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=openmind
      - POSTGRES_PASSWORD=openmind
      - POSTGRES_DB=open-mind
    volumes:
      - postgres-openmind:/var/lib/postgresql/data

volumes:
  openmind:

  openmind_storage:

  postgres-openmind:

